interface DonorData {
  donorId: number;
  donorName: string;
  genderFlag: string;
  donorAge: number;
  donationDate: string;
  replyCount: number;
  letterCount: number;
}

export const donorData: DonorData[] = [
  {
    donorId: 1,
    donorName: "김민수",
    genderFlag: "M",
    donorAge: 37,
    donationDate: "2025-06-09",
    replyCount: 12,
    letterCount: 28,
  },
  {
    donorId: 2,
    donorName: "이지은",
    genderFlag: "F",
    donorAge: 24,
    donationDate: "2025-06-08",
    replyCount: 5,
    letterCount: 17,
  },
  {
    donorId: 3,
    donorName: "박준영",
    genderFlag: "M",
    donorAge: 42,
    donationDate: "2025-06-05",
    replyCount: 18,
    letterCount: 9,
  },
  {
    donorId: 4,
    donorName: "정지우",
    genderFlag: "F",
    donorAge: 31,
    donationDate: "2025-06-07",
    replyCount: 3,
    letterCount: 25,
  },
  {
    donorId: 5,
    donorName: "최현우",
    genderFlag: "M",
    donorAge: 29,
    donationDate: "2025-06-11",
    replyCount: 7,
    letterCount: 14,
  },
  {
    donorId: 6,
    donorName: "김서연",
    genderFlag: "F",
    donorAge: 45,
    donationDate: "2024-04-06",
    replyCount: 9,
    letterCount: 27,
  },
  {
    donorId: 7,
    donorName: "이준호",
    genderFlag: "M",
    donorAge: 33,
    donationDate: "2024-09-14",
    replyCount: 13,
    letterCount: 17,
  },
  {
    donorId: 8,
    donorName: "박지훈",
    genderFlag: "M",
    donorAge: 35,
    donationDate: "2025-05-30",
    replyCount: 10,
    letterCount: 1,
  },
  {
    donorId: 9,
    donorName: "정다현",
    genderFlag: "F",
    donorAge: 46,
    donationDate: "2024-07-29",
    replyCount: 7,
    letterCount: 22,
  },
  {
    donorId: 10,
    donorName: "최민준",
    genderFlag: "M",
    donorAge: 38,
    donationDate: "2024-04-11",
    replyCount: 12,
    letterCount: 15,
  },
  {
    donorId: 11,
    donorName: "김하은",
    genderFlag: "F",
    donorAge: 46,
    donationDate: "2025-03-21",
    replyCount: 1,
    letterCount: 9,
  },
  {
    donorId: 12,
    donorName: "이수빈",
    genderFlag: "F",
    donorAge: 27,
    donationDate: "2024-12-03",
    replyCount: 8,
    letterCount: 18,
  },
  {
    donorId: 13,
    donorName: "박서준",
    genderFlag: "M",
    donorAge: 41,
    donationDate: "2024-08-17",
    replyCount: 14,
    letterCount: 12,
  },
  {
    donorId: 14,
    donorName: "정예린",
    genderFlag: "F",
    donorAge: 22,
    donationDate: "2025-01-29",
    replyCount: 4,
    letterCount: 7,
  },
  {
    donorId: 15,
    donorName: "최지호",
    genderFlag: "M",
    donorAge: 43,
    donationDate: "2024-11-09",
    replyCount: 17,
    letterCount: 28,
  },
  {
    donorId: 16,
    donorName: "김현우",
    genderFlag: "M",
    donorAge: 39,
    donationDate: "2025-05-12",
    replyCount: 6,
    letterCount: 11,
  },
  {
    donorId: 17,
    donorName: "이서연",
    genderFlag: "F",
    donorAge: 26,
    donationDate: "2024-06-19",
    replyCount: 10,
    letterCount: 24,
  },
  {
    donorId: 18,
    donorName: "박동현",
    genderFlag: "M",
    donorAge: 48,
    donationDate: "2025-02-03",
    replyCount: 3,
    letterCount: 5,
  },
  {
    donorId: 19,
    donorName: "정지민",
    genderFlag: "F",
    donorAge: 30,
    donationDate: "2024-10-27",
    replyCount: 5,
    letterCount: 19,
  },
  {
    donorId: 20,
    donorName: "최윤서",
    genderFlag: "F",
    donorAge: 25,
    donationDate: "2024-03-15",
    replyCount: 2,
    letterCount: 13,
  },
  {
    donorId: 21,
    donorName: "김태현",
    genderFlag: "M",
    donorAge: 47,
    donationDate: "2025-04-22",
    replyCount: 11,
    letterCount: 16,
  },
  {
    donorId: 22,
    donorName: "이주원",
    genderFlag: "M",
    donorAge: 32,
    donationDate: "2024-02-08",
    replyCount: 9,
    letterCount: 20,
  },
  {
    donorId: 23,
    donorName: "박수빈",
    genderFlag: "F",
    donorAge: 28,
    donationDate: "2025-05-23",
    replyCount: 7,
    letterCount: 9,
  },
  {
    donorId: 24,
    donorName: "정준호",
    genderFlag: "M",
    donorAge: 44,
    donationDate: "2024-07-05",
    replyCount: 12,
    letterCount: 27,
  },
  {
    donorId: 25,
    donorName: "최예지",
    genderFlag: "F",
    donorAge: 23,
    donationDate: "2025-01-13",
    replyCount: 6,
    letterCount: 14,
  },
  {
    donorId: 26,
    donorName: "김지우",
    genderFlag: "F",
    donorAge: 36,
    donationDate: "2024-12-26",
    replyCount: 8,
    letterCount: 22,
  },
  {
    donorId: 27,
    donorName: "이도윤",
    genderFlag: "M",
    donorAge: 40,
    donationDate: "2025-03-08",
    replyCount: 15,
    letterCount: 10,
  },
  {
    donorId: 28,
    donorName: "박서윤",
    genderFlag: "F",
    donorAge: 27,
    donationDate: "2024-08-24",
    replyCount: 4,
    letterCount: 17,
  },
  {
    donorId: 29,
    donorName: "정민재",
    genderFlag: "M",
    donorAge: 33,
    donationDate: "2025-04-30",
    replyCount: 10,
    letterCount: 3,
  },
  {
    donorId: 30,
    donorName: "최유진",
    genderFlag: "F",
    donorAge: 31,
    donationDate: "2024-06-11",
    replyCount: 7,
    letterCount: 21,
  },
  {
    donorId: 31,
    donorName: "김동준",
    genderFlag: "M",
    donorAge: 45,
    donationDate: "2025-02-17",
    replyCount: 13,
    letterCount: 8,
  },
  {
    donorId: 32,
    donorName: "이수현",
    genderFlag: "F",
    donorAge: 38,
    donationDate: "2024-09-30",
    replyCount: 6,
    letterCount: 12,
  },
  {
    donorId: 33,
    donorName: "박예준",
    genderFlag: "M",
    donorAge: 29,
    donationDate: "2025-01-05",
    replyCount: 9,
    letterCount: 16,
  },
  {
    donorId: 34,
    donorName: "정서연",
    genderFlag: "F",
    donorAge: 34,
    donationDate: "2024-03-27",
    replyCount: 11,
    letterCount: 7,
  },
  {
    donorId: 35,
    donorName: "최재윤",
    genderFlag: "M",
    donorAge: 42,
    donationDate: "2025-05-18",
    replyCount: 8,
    letterCount: 19,
  },
  {
    donorId: 36,
    donorName: "김수지",
    genderFlag: "F",
    donorAge: 26,
    donationDate: "2024-11-21",
    replyCount: 3,
    letterCount: 11,
  },
  {
    donorId: 37,
    donorName: "이현우",
    genderFlag: "M",
    donorAge: 39,
    donationDate: "2025-04-03",
    replyCount: 14,
    letterCount: 23,
  },
  {
    donorId: 38,
    donorName: "박민서",
    genderFlag: "M",
    donorAge: 30,
    donationDate: "2024-07-14",
    replyCount: 5,
    letterCount: 15,
  },
  {
    donorId: 39,
    donorName: "정예은",
    genderFlag: "F",
    donorAge: 43,
    donationDate: "2025-03-16",
    replyCount: 7,
    letterCount: 28,
  },
  {
    donorId: 40,
    donorName: "최준호",
    genderFlag: "M",
    donorAge: 35,
    donationDate: "2024-10-08",
    replyCount: 10,
    letterCount: 6,
  },
  {
    donorId: 41,
    donorName: "김지민",
    genderFlag: "F",
    donorAge: 24,
    donationDate: "2025-02-22",
    replyCount: 12,
    letterCount: 9,
  },
  {
    donorId: 42,
    donorName: "이다현",
    genderFlag: "F",
    donorAge: 41,
    donationDate: "2024-08-02",
    replyCount: 8,
    letterCount: 17,
  },
  {
    donorId: 43,
    donorName: "박서진",
    genderFlag: "M",
    donorAge: 28,
    donationDate: "2025-01-17",
    replyCount: 6,
    letterCount: 10,
  },
  {
    donorId: 44,
    donorName: "정윤서",
    genderFlag: "F",
    donorAge: 37,
    donationDate: "2024-12-09",
    replyCount: 9,
    letterCount: 14,
  },
  {
    donorId: 45,
    donorName: "최시우",
    genderFlag: "M",
    donorAge: 32,
    donationDate: "2025-05-02",
    replyCount: 11,
    letterCount: 8,
  },
  {
    donorId: 46,
    donorName: "김하윤",
    genderFlag: "F",
    donorAge: 29,
    donationDate: "2024-09-07",
    replyCount: 7,
    letterCount: 22,
  },
  {
    donorId: 47,
    donorName: "이민준",
    genderFlag: "M",
    donorAge: 44,
    donationDate: "2025-04-15",
    replyCount: 13,
    letterCount: 16,
  },
  {
    donorId: 48,
    donorName: "박서아",
    genderFlag: "F",
    donorAge: 25,
    donationDate: "2024-06-30",
    replyCount: 5,
    letterCount: 19,
  },
  {
    donorId: 49,
    donorName: "정준서",
    genderFlag: "M",
    donorAge: 36,
    donationDate: "2025-03-29",
    replyCount: 10,
    letterCount: 7,
  },
  {
    donorId: 50,
    donorName: "최서현",
    genderFlag: "F",
    donorAge: 40,
    donationDate: "2024-11-13",
    replyCount: 12,
    letterCount: 21,
  },
  {
    donorId: 51,
    donorName: "김예린",
    genderFlag: "F",
    donorAge: 27,
    donationDate: "2025-05-27",
    replyCount: 8,
    letterCount: 13,
  },
  {
    donorId: 52,
    donorName: "이시윤",
    genderFlag: "M",
    donorAge: 33,
    donationDate: "2024-07-22",
    replyCount: 14,
    letterCount: 18,
  },
  {
    donorId: 53,
    donorName: "박민지",
    genderFlag: "F",
    donorAge: 45,
    donationDate: "2025-02-09",
    replyCount: 6,
    letterCount: 10,
  },
  {
    donorId: 54,
    donorName: "정우진",
    genderFlag: "M",
    donorAge: 31,
    donationDate: "2024-10-19",
    replyCount: 9,
    letterCount: 15,
  },
];
