const plugin = require("tailwindcss/plugin");

module.exports = plugin(
  function ({ addBase, addUtilities, addComponents, theme }) {
    addBase({
      ":root": {
        "--krds-color-primary-5": "#ecf2fe",
        "--krds-color-primary-10": "#d8e5fd",
        "--krds-color-primary-20": "#b1cefb",
        "--krds-color-primary-30": "#86aff9",
        "--krds-color-primary-40": "#4c87f6",
        "--krds-color-primary-50": "#256ef4",
        "--krds-color-primary-60": "#0b50d0",
        "--krds-color-primary-70": "#083891",
        "--krds-color-primary-80": "#052561",
        "--krds-color-primary-90": "#03163a",
        "--krds-color-primary-95": "#020f27",

        "--krds-color-secondary-5": "#eef2f7",
        "--krds-color-secondary-10": "#d6e0eb",
        "--krds-color-secondary-20": "#bacbde",
        "--krds-color-secondary-30": "#90b0d5",
        "--krds-color-secondary-40": "#6b96c7",
        "--krds-color-secondary-50": "#346fb2",
        "--krds-color-secondary-60": "#1c589c",
        "--krds-color-secondary-70": "#063a74",
        "--krds-color-secondary-80": "#052b57",
        "--krds-color-secondary-90": "#031f3f",
        "--krds-color-secondary-95": "#02162c",

        "--krds-color-gray-0": "#ffffff",
        "--krds-color-gray-5": "#f4f5f6",
        "--krds-color-gray-10": "#e6e8ea",
        "--krds-color-gray-20": "#cdd1d5",
        "--krds-color-gray-30": "#b1b8be",
        "--krds-color-gray-40": "#8a949e",
        "--krds-color-gray-50": "#6d7882",
        "--krds-color-gray-60": "#58616a",
        "--krds-color-gray-70": "#464c53",
        "--krds-color-gray-80": "#33363d",
        "--krds-color-gray-90": "#1e2124",
        "--krds-color-gray-95": "#131416",
        "--krds-color-gray-100": "#000000",

        "--krds-color-alpha-black100": "#000000",
        "--krds-color-alpha-black75": "#000000bf",
        "--krds-color-alpha-black50": "#00000080",
        "--krds-color-alpha-black25": "#00000040",
        "--krds-color-alpha-black10": "#0000001a",
        "--krds-color-alpha-black0": "#00000000",
        "--krds-color-alpha-white100": "#ffffff",
        "--krds-color-alpha-white75": "#ffffffbf",
        "--krds-color-alpha-white50": "#ffffff80",
        "--krds-color-alpha-white25": "#ffffff40",
        "--krds-color-alpha-white10": "#ffffff1a",
        "--krds-color-alpha-white0": "#ffffff00",

        "--krds-color-danger-5": "#fdefec",
        "--krds-color-danger-10": "#fcdfd9",
        "--krds-color-danger-20": "#f7afa1",
        "--krds-color-danger-30": "#f48771",
        "--krds-color-danger-40": "#f05f42",
        "--krds-color-danger-50": "#de3412",
        "--krds-color-danger-60": "#bd2c0f",
        "--krds-color-danger-70": "#8a240f",
        "--krds-color-danger-80": "#5c180a",
        "--krds-color-danger-90": "#390d05",
        "--krds-color-danger-95": "#260903",

        "--krds-color-information-5": "#e7f4fe",
        "--krds-color-information-10": "#d3ebfd",
        "--krds-color-information-20": "#9ed2fa",
        "--krds-color-information-30": "#5fb5f7",
        "--krds-color-information-40": "#2098f3",
        "--krds-color-information-50": "#0b78cb",
        "--krds-color-information-60": "#096ab3",
        "--krds-color-information-70": "#085691",
        "--krds-color-information-80": "#053961",
        "--krds-color-information-90": "#03253f",
        "--krds-color-information-95": "#021a2c",

        "--krds-color-warning-5": "#fff3db",
        "--krds-color-warning-10": "#ffe0a3",
        "--krds-color-warning-20": "#ffc95c",
        "--krds-color-warning-30": "#ffb114",
        "--krds-color-warning-40": "#c78500",
        "--krds-color-warning-50": "#9e6a00",
        "--krds-color-warning-60": "#8a5c00",
        "--krds-color-warning-70": "#614100",
        "--krds-color-warning-80": "#422c00",
        "--krds-color-warning-90": "#2e1f00",
        "--krds-color-warning-95": "#241800",

        "--krds-color-success-5": "#eaf6ec",
        "--krds-color-success-10": "#d8eedd",
        "--krds-color-success-20": "#a9dab4",
        "--krds-color-success-30": "#7ec88e",
        "--krds-color-success-40": "#3fa654",
        "--krds-color-success-50": "#228738",
        "--krds-color-success-60": "#267337",
        "--krds-color-success-70": "#285d33",
        "--krds-color-success-80": "#1f4727",
        "--krds-color-success-90": "#122b18",
        "--krds-color-success-95": "#0e2012",

        "--krds-color-point-5": "#fbeff0",
        "--krds-color-point-10": "#f5d6d9",
        "--krds-color-point-20": "#ebadb2",
        "--krds-color-point-30": "#e0858c",
        "--krds-color-point-40": "#d65c66",
        "--krds-color-point-50": "#d63d4a",
        "--krds-color-point-60": "#ab2b36",
        "--krds-color-point-70": "#7a1f26",
        "--krds-color-point-80": "#521419",
        "--krds-color-point-90": "#310c0f",
        "--krds-color-point-95": "#21080a",

        "--krds-color-graphic-10": "#e5ecf9",
        "--krds-color-graphic-30": "#98acc5",
        "--krds-color-graphic-50": "#61758f",
        "--krds-color-graphic-70": "#39506c",
        "--krds-color-graphic-90": "#223a58",

        /* Font sizes - Mobile 기준 */
        "--krds-font-display-large": "44px",
        "--krds-font-display-medium": "32px",
        "--krds-font-display-small": "28px",

        "--krds-font-heading-xlarge": "28px",
        "--krds-font-heading-large": "24px",
        "--krds-font-heading-medium": "22px",
        "--krds-font-heading-small": "19px",
        "--krds-font-heading-xsmall": "17px",
        "--krds-font-heading-xxsmall": "15px",

        "--krds-font-body-large": "19px",
        "--krds-font-body-medium": "17px",
        "--krds-font-body-small": "15px",
        "--krds-font-body-xsmall": "13px",

        /* Font weight */
        "--krds-typo-font-weight-regular": "400",
        "--krds-typo-font-weight-bold": "700",

        /* Line Height */
        "--krds-line-height": "1.5",

        /* Letter Spacing */
        "--krds-typo-letter-spacing-0": "0px",
        "--krds-typo-letter-spacing-1": "1px",

        /* Radius */
        "--krds-radius-1": "2px",
        "--krds-radius-2": "4px",
        "--krds-radius-3": "6px",
        "--krds-radius-4": "8px",
        "--krds-radius-5": "10px",
        "--krds-radius-6": "12px",

        /* Gap */
        "--krds-gap-1": "2px",
        "--krds-gap-2": "4px",
        "--krds-gap-3": "8px",
        "--krds-gap-4": "10px",
        "--krds-gap-5": "12px",
        "--krds-gap-6": "16px",
        "--krds-gap-7": "20px",
        "--krds-gap-8": "24px",
        "--krds-gap-9": "32px",
        "--krds-gap-10": "40px",
        "--krds-gap-11": "64px",
        "--krds-gap-12": "80px",

        /* Padding */
        "--krds-padding-1": "2px",
        "--krds-padding-2": "4px",
        "--krds-padding-3": "8px",
        "--krds-padding-4": "10px",
        "--krds-padding-5": "12px",
        "--krds-padding-6": "16px",
        "--krds-padding-7": "20px",
        "--krds-padding-8": "24px",
        "--krds-padding-9": "32px",
        "--krds-padding-10": "40px",

        /* Shadow */
        "--krds-shadow-1": "0px 2px 2px rgba(0, 0, 0, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.05)",
        "--krds-shadow-2": "0px 4px 8px rgba(0, 0, 0, 0.08), 0px 2px 2px rgba(0, 0, 0, 0.05)",
        "--krds-shadow-3": "0px 8px 16px rgba(0, 0, 0, 0.12), 0px 2px 2px rgba(0, 0, 0, 0.08)",
        "--krds-shadow-4": "0px 16px 24px rgba(0, 0, 0, 0.12), 0px 2px 2px rgba(0, 0, 0, 0.08)",

        /* Icon Size */
        "--krds-icon-size-12": "12px",
        "--krds-icon-size-16": "16px",
        "--krds-icon-size-20": "20px",
        "--krds-icon-size-24": "24px",
        "--krds-icon-size-32": "32px",
        "--krds-icon-size-40": "40px",
      },
    });
    addBase({
      "@media (min-width: 768px)": {
        ":root": {
          "--krds-font-display-large": "60px",
          "--krds-font-display-medium": "44px",
          "--krds-font-display-small": "36px",

          "--krds-font-heading-xlarge": "40px",
          "--krds-font-heading-large": "32px",
          "--krds-font-heading-medium": "24px",
          "--krds-font-heading-small": "19px",
          "--krds-font-heading-xsmall": "17px",
          "--krds-font-heading-xxsmall": "15px",

          "--krds-font-body-large": "19px",
          "--krds-font-body-medium": "17px",
          "--krds-font-body-small": "15px",
          "--krds-font-body-xsmall": "13px",
        },
      },
    });
  },
  {
    theme: {
      extend: {
        colors: {
          primary: {
            5: "var(--krds-color-primary-5)",
            10: "var(--krds-color-primary-10)",
            20: "var(--krds-color-primary-20)",
            30: "var(--krds-color-primary-30)",
            40: "var(--krds-color-primary-40)",
            50: "var(--krds-color-primary-50)",
            60: "var(--krds-color-primary-60)",
            70: "var(--krds-color-primary-70)",
            80: "var(--krds-color-primary-80)",
            90: "var(--krds-color-primary-90)",
            95: "var(--krds-color-primary-95)",
          },
          secondary: {
            5: "var(--krds-color-secondary-5)",
            10: "var(--krds-color-secondary-10)",
            20: "var(--krds-color-secondary-20)",
            30: "var(--krds-color-secondary-30)",
            40: "var(--krds-color-secondary-40)",
            50: "var(--krds-color-secondary-50)",
            60: "var(--krds-color-secondary-60)",
            70: "var(--krds-color-secondary-70)",
            80: "var(--krds-color-secondary-80)",
            90: "var(--krds-color-secondary-90)",
            95: "var(--krds-color-secondary-95)",
          },
          gray: {
            0: "var(--krds-color-gray-0)",
            5: "var(--krds-color-gray-5)",
            10: "var(--krds-color-gray-10)",
            20: "var(--krds-color-gray-20)",
            30: "var(--krds-color-gray-30)",
            40: "var(--krds-color-gray-40)",
            50: "var(--krds-color-gray-50)",
            60: "var(--krds-color-gray-60)",
            70: "var(--krds-color-gray-70)",
            80: "var(--krds-color-gray-80)",
            90: "var(--krds-color-gray-90)",
            95: "var(--krds-color-gray-95)",
          },
          alpha: {
            black100: "var(--krds-color-alpha-black100)",
            black75: "var(--krds-color-alpha-black75)",
            black50: "var(--krds-color-alpha-black50)",
            black25: "var(--krds-color-alpha-black25)",
            black10: "var(--krds-color-alpha-black10)",
            black0: "var(--krds-color-alpha-black0)",
            white100: "var(--krds-color-alpha-white100)",
            white75: "var(--krds-color-alpha-white75)",
            white50: "var(--krds-color-alpha-white50)",
            white25: "var(--krds-color-alpha-white25)",
            white10: "var(--krds-color-alpha-white10)",
            white0: "var(--krds-color-alpha-white0)",
          },
          danger: {
            5: "var(--krds-color-danger-5)",
            10: "var(--krds-color-danger-10)",
            20: "var(--krds-color-danger-20)",
            30: "var(--krds-color-danger-30)",
            40: "var(--krds-color-danger-40)",
            50: "var(--krds-color-danger-50)",
            60: "var(--krds-color-danger-60)",
            70: "var(--krds-color-danger-70)",
            80: "var(--krds-color-danger-80)",
            90: "var(--krds-color-danger-90)",
            95: "var(--krds-color-danger-95)",
          },
          information: {
            5: "var(--krds-color-information-5)",
            10: "var(--krds-color-information-10)",
            20: "var(--krds-color-information-20)",
            30: "var(--krds-color-information-30)",
            40: "var(--krds-color-information-40)",
            50: "var(--krds-color-information-50)",
            60: "var(--krds-color-information-60)",
            70: "var(--krds-color-information-70)",
            80: "var(--krds-color-information-80)",
            90: "var(--krds-color-information-90)",
            95: "var(--krds-color-information-95)",
          },
          success: {
            5: "var(--krds-color-success-5)",
            10: "var(--krds-color-success-10)",
            20: "var(--krds-color-success-20)",
            30: "var(--krds-color-success-30)",
            40: "var(--krds-color-success-40)",
            50: "var(--krds-color-success-50)",
            60: "var(--krds-color-success-60)",
            70: "var(--krds-color-success-70)",
            80: "var(--krds-color-success-80)",
            90: "var(--krds-color-success-90)",
            95: "var(--krds-color-success-95)",
          },
          point: {
            5: "var(--krds-color-point-5)",
            10: "var(--krds-color-point-10)",
            20: "var(--krds-color-point-20)",
            30: "var(--krds-color-point-30)",
            40: "var(--krds-color-point-40)",
            50: "var(--krds-color-point-50)",
            60: "var(--krds-color-point-60)",
            70: "var(--krds-color-point-70)",
            80: "var(--krds-color-point-80)",
            90: "var(--krds-color-point-90)",
            95: "var(--krds-color-point-95)",
          },
          graphic: {
            10: "var(--krds-color-graphic-10)",
            30: "var(--krds-color-graphic-30)",
            50: "var(--krds-color-graphic-50)",
            70: "var(--krds-color-graphic-70)",
            90: "var(--krds-color-graphic-90)",
          },
        },

        //폰트 사이즈
        fontSize: {
          "d-lg": "var(--krds-font-display-large)",
          "d-md": "var(--krds-font-display-medium)",
          "d-sm": "var(--krds-font-display-small)",

          "h-xl": "var(--krds-font-heading-xlarge)",
          "h-lg": "var(--krds-font-heading-large)",
          "h-md": "var(--krds-font-heading-medium)",
          "h-sm": "var(--krds-font-heading-small)",
          "h-xs": "var(--krds-font-heading-xsmall)",
          "h-2xs": "var(--krds-font-heading-xxsmall)",

          "b-lg": "var(--krds-font-body-large)",
          "b-md": "var(--krds-font-body-medium)",
          "b-sm": "var(--krds-font-body-small)",
          "b-xs": "var(--krds-font-body-xsmall)",
        },

        //폰트 굵기
        fontWeight: {
          reg: "var(--krds-typo-font-weight-regular)",
          bold: "var(--krds-typo-font-weight-bold)",
        },

        //자간
        letterSpacing: {
          0: "var(--krds-typo-letter-spacing-0)",
          1: "var(--krds-typo-letter-spacing-1)",
        },

        //줄간격
        lineHeight: {
          base: "var(--krds-line-height)",
        },

        //border radius
        borderRadius: {
          r1: "var(--krds-radius-1)",
          r2: "var(--krds-radius-2)",
          r3: "var(--krds-radius-3)",
          r4: "var(--krds-radius-4)",
          r5: "var(--krds-radius-5)",
          r6: "var(--krds-radius-6)",
        },

        // 간격
        spacing: {
          // gap
          g1: "var(--krds-gap-1)",
          g2: "var(--krds-gap-2)",
          g3: "var(--krds-gap-3)",
          g4: "var(--krds-gap-4)",
          g5: "var(--krds-gap-5)",
          g6: "var(--krds-gap-6)",
          g7: "var(--krds-gap-7)",
          g8: "var(--krds-gap-8)",
          g9: "var(--krds-gap-9)",
          g10: "var(--krds-gap-10)",
          g11: "var(--krds-gap-11)",
          g12: "var(--krds-gap-12)",

          // padding (같은 spacing으로 활용)
          p1: "var(--krds-padding-1)",
          p2: "var(--krds-padding-2)",
          p3: "var(--krds-padding-3)",
          p4: "var(--krds-padding-4)",
          p5: "var(--krds-padding-5)",
          p6: "var(--krds-padding-6)",
          p7: "var(--krds-padding-7)",
          p8: "var(--krds-padding-8)",
          p9: "var(--krds-padding-9)",
          p10: "var(--krds-padding-10)",

          // icon size
          icon1: "var(--krds-icon-size-12)",
          icon2: "var(--krds-icon-size-16)",
          icon3: "var(--krds-icon-size-20)",
          icon4: "var(--krds-icon-size-24)",
          icon5: "var(--krds-icon-size-32)",
          icon6: "var(--krds-icon-size-40)",
        },

        // 그림자
        boxShadow: {
          s1: "var(--krds-shadow-1)",
          s2: "var(--krds-shadow-2)",
          s3: "var(--krds-shadow-3)",
          s4: "var(--krds-shadow-4)",
        },
      },
    },
  },
);
